const consolasyjuegos = [
  {
    nameProduct: 'Family Game',
    brand: 'Nintendo',
    yearOfProduction: 1990,
    category: 'Consolas y Juegos',
    description: 'Consola clásica / (Lorem Ipsum)',
    price: '100',
    namePhoto: {
      1: 'consola1-1.jpeg',
      2: 'consola1-2.jpeg',
    },
  },
  {
    nameProduct: 'Play Station 1',
    brand: 'Sony',
    yearOfProduction: 1994,
    category: 'Consolas y Juegos',
    description: 'Consola clásica / (Lorem Ipsum)',
    price: '150',
    namePhoto: {
      1: 'consola2-1.jpeg',
      2: 'consola2-2.jpeg',
    },
  },
  {
    nameProduct: 'Play Station ',
    brand: 'Sony',
    yearOfProduction: 1999,
    category: 'Consolas y Juegos',
    description: 'Consola clásica con 64 juegos',
    price: '100',
    namePhoto: {
      1: 'consola3-1.jpeg',
      2: 'consola3-2.jpeg',
    },
  },
  {
    nameProduct: 'Play Station 3',
    brand: 'Sony',
    yearOfProduction: 2008,
    category: 'Consolas y Juegos',
    description: 'Consola clásica / (Lorem Ipsum)',
    price: '80',
    namePhoto: {
      1: 'consola4-1.jpeg',
      2: 'consola4-2.jpeg',
    },
  },
  {
    nameProduct: 'Game Cube',
    brand: 'SNintendo',
    yearOfProduction: 2003,
    category: 'Consolas y Juegos',
    description: 'Consola clásica con juego',
    price: '100',
    namePhoto: {
      1: 'consola5-1.jpeg',
      2: 'consola5-2.jpeg',
    },
  },
  {
    nameProduct: 'Xbox',
    brand: 'Microsoft',
    yearOfProduction: 2003,
    category: 'Consolas y Juegos',
    description: 'Consola clásica con 2 mandos',
    price: '90',
    namePhoto: {
      1: 'consola6-1.jpeg',
      2: 'consola6-2.jpeg',
    },
  },
  {
    nameProduct: 'Atari 2600',
    brand: 'Atari',
    yearOfProduction: 1986,
    category: 'Consolas y Juegos',
    description: 'Consola histórica con 2 mandos y juegos',
    price: '500',
    namePhoto: {
      1: 'consola7-1.jpeg',
      2: 'consola7-2.jpeg',
    },
  },
  {
    nameProduct: 'Game Boy',
    brand: 'Nintendo',
    yearOfProduction: 2000,
    category: 'Consolas y Juegos',
    description: 'Consola clásica de viaje con juegos',
    price: '50',
    namePhoto: {
      1: 'consola8-1.jpeg',
      2: 'consola8-2.jpeg',
    },
  },
  {
    nameProduct: 'Super Nintendo',
    brand: 'Nintendo',
    yearOfProduction: 1998,
    category: 'Consolas y Juegos',
    description: 'Consola clásica con 2 mandos',
    price: '90',
    namePhoto: {
      1: 'consola9-1.jpeg',
      2: 'consola9-2.jpeg',
    },
  },
  {
    nameProduct: 'PSP',
    brand: 'Sony',
    yearOfProduction: 2006,
    category: 'Consolas y Juegos',
    description: 'Consola clásica de viaje',
    price: '50',
    namePhoto: {
      1: 'consola10-1.jpeg',
      2: 'consola10-2.jpeg',
    },
  },
];
